module.exports = {
  apps: [{
    name: 'wa-bot-ndxstore',
    script: './index.js',
    node_args: '--max-old-space-size=512',
    watch: false,
    max_memory_restart: '512M',
    restart_delay: 5000,
    max_restarts: 10,
    min_uptime: 10000,
    kill_timeout: 30000,
    wait_ready: false,
    listen_timeout: 30000,
    exp_backoff_restart_delay: 5000,
    merge_logs: true,
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    error_file: '/dev/null',
    out_file: '/dev/null',
    combine_logs: true,
    shutdown_with_message: true,
    env: {
      NODE_ENV: 'production',
      LOG_CONSOLE: 'false',
    },
  }],
};
